# Generated by Django 2.2 on 2019-12-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddyApp', '0003_auto_20191221_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='item',
            new_name='plan',
        ),
    ]
