# Generated by Django 2.2 on 2019-12-21 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddyApp', '0004_auto_20191221_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='isJoined',
            new_name='isPlanned',
        ),
    ]
