# Generated by Django 2.2 on 2019-12-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddyApp', '0005_auto_20191221_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='isPlanned',
            new_name='isJoined',
        ),
    ]
